### ISSUE TITLE
Instant objects cannot be sent because of serialization error

### ISSUE THREAD

**Issue by brightspectrum** [deppan/socket.io-java-emitter#1]
Objects containing the Instant class cannot be serialized and sent. It looks like maybe the ObjectMapper used in MsgPackParser needs to have the JavaTimeModule registered.

io.github.deppan.Emitter                 : emit: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.Instant` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"

**Comment by deppan** [comment]
Thanks for your feedback, I have fixed this issue, please update the library and retry it.
